for k in $(seq 1 30)
do
  python train.py --dataset="iemocap" --modalities="atv" --from_begin --epochs=20 --learning_rate=0.00025 --optimizer="adam" --drop_rate=0.5 --batch_size=10 --rnn="transformer" --use_speaker --edge_type="temp_multi" --wp=12 --wf=9 --gcn_conv="rgcn" --use_graph_transformer --graph_transformer_nheads=7 --use_mmt --num_crossmodal=2 --num_self_att=3 --crossmodal_nheads=2 --self_att_nheads=2 --comet_workspace="mattam301" --comet_api_key="Fd1aGmcly8SdDO5Ez4DMyCIt5" --log_in_comet --use_graph_pe="laplacian" --laplacian_k=17
  python train.py --dataset="iemocap" --modalities="atv" --from_begin --epochs=20 --learning_rate=0.00025 --optimizer="adam" --drop_rate=0.5 --batch_size=10 --rnn="transformer" --use_speaker --edge_type="temp_multi" --wp=12 --wf=9 --gcn_conv="rgcn" --use_graph_transformer --graph_transformer_nheads=7 --use_mmt --num_crossmodal=2 --num_self_att=3 --crossmodal_nheads=2 --self_att_nheads=2 --comet_workspace="mattam301" --comet_api_key="Fd1aGmcly8SdDO5Ez4DMyCIt5" --log_in_comet --use_graph_pe="laplacian" --laplacian_k=17  
  python train.py --dataset="iemocap" --modalities="atv" --from_begin --epochs=20 --learning_rate=0.00025 --optimizer="adam" --drop_rate=0.5 --batch_size=10 --rnn="transformer" --use_speaker --edge_type="temp_multi" --wp=12 --wf=9 --gcn_conv="rgcn" --use_graph_transformer --graph_transformer_nheads=7 --use_mmt --num_crossmodal=2 --num_self_att=3 --crossmodal_nheads=2 --self_att_nheads=2 --comet_workspace="mattam301" --comet_api_key="Fd1aGmcly8SdDO5Ez4DMyCIt5" --log_in_comet --use_graph_pe="laplacian" --laplacian_k=17
  python train.py --dataset="iemocap" --modalities="atv" --from_begin --epochs=20 --learning_rate=0.00025 --optimizer="adam" --drop_rate=0.5 --batch_size=10 --rnn="transformer" --use_speaker --edge_type="temp_multi" --wp=12 --wf=9 --gcn_conv="rgcn" --use_graph_transformer --graph_transformer_nheads=7 --use_mmt --num_crossmodal=2 --num_self_att=3 --crossmodal_nheads=2 --self_att_nheads=2 --comet_workspace="mattam301" --comet_api_key="Fd1aGmcly8SdDO5Ez4DMyCIt5" --log_in_comet --use_graph_pe="laplacian" --laplacian_k=17  
  python train.py --dataset="iemocap" --modalities="atv" --from_begin --epochs=20 --learning_rate=0.00025 --optimizer="adam" --drop_rate=0.5 --batch_size=10 --rnn="transformer" --use_speaker --edge_type="temp_multi" --wp=12 --wf=9 --gcn_conv="rgcn" --use_graph_transformer --graph_transformer_nheads=7 --use_mmt --num_crossmodal=2 --num_self_att=3 --crossmodal_nheads=2 --self_att_nheads=2 --comet_workspace="mattam301" --comet_api_key="Fd1aGmcly8SdDO5Ez4DMyCIt5" --log_in_comet --use_graph_pe="laplacian" --laplacian_k=17
  python train.py --dataset="iemocap" --modalities="atv" --from_begin --epochs=20 --learning_rate=0.00025 --optimizer="adam" --drop_rate=0.5 --batch_size=10 --rnn="transformer" --use_speaker --edge_type="temp_multi" --wp=12 --wf=9 --gcn_conv="rgcn" --use_graph_transformer --graph_transformer_nheads=7 --use_mmt --num_crossmodal=2 --num_self_att=3 --crossmodal_nheads=2 --self_att_nheads=2 --comet_workspace="mattam301" --comet_api_key="Fd1aGmcly8SdDO5Ez4DMyCIt5" --log_in_comet --use_graph_pe="laplacian" --laplacian_k=17
  python train.py --dataset="iemocap" --modalities="atv" --from_begin --epochs=20 --learning_rate=0.00025 --optimizer="adam" --drop_rate=0.5 --batch_size=10 --rnn="transformer" --use_speaker --edge_type="temp_multi" --wp=12 --wf=9 --gcn_conv="rgcn" --use_graph_transformer --graph_transformer_nheads=7 --use_mmt --num_crossmodal=2 --num_self_att=3 --crossmodal_nheads=2 --self_att_nheads=2 --comet_workspace="mattam301" --comet_api_key="Fd1aGmcly8SdDO5Ez4DMyCIt5" --log_in_comet --use_graph_pe="laplacian" --laplacian_k=17
  
  # python train.py --dataset="iemocap_roberta" --modalities="atv" --from_begin --epochs=50 --learning_rate=0.00025 --optimizer="adam" --drop_rate=0.5 --batch_size=10 --rnn="transformer" --use_speaker --edge_type="temp_multi" --wp=11 --wf=9 --gcn_conv="rgcn" --use_graph_transformer --graph_transformer_nheads=7 --use_mmt --num_crossmodal=2 --num_self_att=3 --crossmodal_nheads=2 --self_att_nheads=2 
done
